#!/bin/bash


killall rfcomm
killall bluetoothd

if ! hciconfig hci0; then
	for cnt in $(seq 3); do
		hciattach ttyS0 bcm43xx 115200 noflow && break
	done
fi

hciconfig hci0 up 

/usr/libexec/bluetooth/bluetoothd --compat &

sleep 1


rfcomm watch hci0 22 /sbin/getty -L {} 115200 vt100 &

hciconfig hci0 piscan
sdptool add --channel 22 SP
